### ISSUE TITLE
大家有笔记或者博客可以一起提交

### ISSUE THREAD

**Issue by CharonChui** [CharonChui/AndroidNote#1]
希望大家也多多提交。互相学习

**Comment by bboyfeiyu** [comment]
@CharonChui hi , www.devtf.cn 可以转载您的文章吗？

**Comment by CharonChui** [comment]
您好，只要标明出处，可以转载的。

**Comment by bboyfeiyu** [comment]
好的，非常感谢 😊

2016-03-01 13:23 GMT+08:00 Charon Chui <notifications@github.com>:
