### ISSUE TITLE
知识大杂烩里通过不断的new出来空白的Toast把系统弄崩溃，这样系统就会重启

### ISSUE THREAD

**Issue by ZhijunLi** [CharonChui/AndroidNote#11]
知识大杂烩里，7手机重启，通过不断的new出来空白的Toast把系统弄崩溃，这样系统就会重启。试验了下，App只是会失去响应，并没有重启哦

**Comment by CharonChui** [comment]
您好，这段代码还是之前在2.x系统手机上试过，在现在的手机中已经无法生效，多谢提醒。
