### ISSUE TITLE
关于 fMP4 视频格式详解中的 MediaParser 工具

### ISSUE THREAD

**Issue by Tackoil** [CharonChui/AndroidNote#33]
您好，今天阅读到这篇文章。
[fMP4视频格式详解](https://github.com/CharonChui/AndroidNote/blob/master/VideoDevelopment/%E8%A7%86%E9%A2%91%E5%B0%81%E8%A3%85%E6%A0%BC%E5%BC%8F/fMP4%E6%A0%BC%E5%BC%8F%E8%AF%A6%E8%A7%A3.md)
想问一下其中截图所使用到的 MediaParser 工具是哪一个？ 是否是mac版本呢？ 谢谢～

**Comment by xiaoyi848699** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Tackoil** [comment]
我找到这个了，但这个软件的问题还有点多。总之感谢。 https://github.com/ksvc/MediaParser
